### ISSUE TITLE
What does the mean of "Configuration_file_content " in the simple-example-blueprint.yaml?

### ISSUE THREAD

**Issue by cissyLlaly** [cloudify-incubator/cloudify-kubernetes-plugin#18]
First, thanks for you writing the kubernetes plugin.
I try to deploy the nginx container in kubernetes by cloudify ; The plugin version is cloudify-kubernetes-plugin-1.0.0， and the yaml file is example/simple-example-blueprint.yaml。I don't know how to fill in the word "Configuration_file_content" .And could you show me some examples?

Anyone Can help me? Thank you very much.

**Comment by michalskalski** [comment]
To "configuration_file_content" you should pass content of `~/.kube/config`. If you don't have one or you want to create dedicated user for Cloudify here you find how to create it: https://stackoverflow.com/a/42186135

I had some problems with passing whole content of this file as it needs to be proper yaml file, so I end up with something like that:

```yaml
dsl_definitions:
  k8s_api_config: &k8s_api_config
    apiVersion: v1
    clusters:
    - cluster:
        server: { get_input: k8s_api_url }
        insecure-skip-tls-verify: true
      name: CLUSTER
    contexts:
    - context:
        cluster: CLUSTER
        user: cloudify-CLUSTER
      name: cloudify-CLUSTER
    current-context: cloudify-CLUSTER
    kind: Config
    preferences: {}
    users:
    - name: cloudify-CLUSTER
      user:
        token: { get_secret: k8s_api_token }

node_templates:
  kubernetes_master:
    type: cloudify.kubernetes.nodes.Master
    properties:
      configuration:
        file_content: *k8s_api_config
```

**Comment by cissyLlaly** [comment]
@michalskalski 
I follow  your guide to pass content of ~/.kube/config

![image](https://user-images.githubusercontent.com/23950070/27822431-292a35f0-60d8-11e7-8fad-763cbb325084.png)

But get the error message:
![image](https://user-images.githubusercontent.com/23950070/27822400-0aa20d88-60d8-11e7-88de-2d9edcebfc5a.png)

I want to know whether the method to realize of  cloudify-kubernetes-plugin has changed?
Thanks.

**Comment by EarthmanT** [comment]
@cissyLlaly I think the error you have shared last "no suitable configuration variant found for {u'api_options': {} } properties is past the client initialization phase and is now related to the resource you are trying to create. Can you share the blueprint?

**Comment by cissyLlaly** [comment]
@EarthmanT Thanks for you reply. I have updated the bp's input parameter "file_content" to "file_name" and the bp's kubernetes_master  edited to "  kubernetes_master:
    type: cloudify.kubernetes.nodes.Master
    properties:
      configuration:
        blueprint_file_name: {get_input: file_name}".
Add the kubernetes configuration file ./kube/config to the bp's pre-packaged archive.
After uploading the blueprint to the manager, i create deployment with a path to a configuration file for the input "file_name" .At last , it 's worked.
But I don't know if I use the "file_content", how should i update the blueprint or fill in the file_content when i create the deployment? thanks.

**Comment by EarthmanT** [comment]
@cissyLlaly 
If you provide the configuration file packaged in the blueprint, the master resource config should look like this:
```yaml
inputs:
  file_name:
    default: files/kube.config
node_templates: 
  kubernetes_master:
    type: cloudify.kubernetes.nodes.Master
    properties:
      configuration:
          blueprint_file_name: {get_input: file_name}
```
The blueprint directory structure would look like this:
```shell
.
├── blueprint.yaml
├── files
│   ├── kube.config
```
